app/views/admin/dashboard/_welcome.html.erb
spec/controllers/admin/dashboard_controller_spec.rb

`Admin::FeedbackController#index` expects a filter to be specified in the [`only` param](https://github.com/moneyadviceservice/publify/blob/d8df2bf923a2faf5fab1e18495573fffb926c2a3/app/controllers/admin/feedback_controller.rb#L8).
__NOTE:__ the `unconfirmed` scope only [exists on Feedback](https://github.com/moneyadviceservice/publify/blob/d8df2bf923a2faf5fab1e18495573fffb926c2a3/app/models/feedback.rb#L28) and [not Comment](https://github.com/moneyadviceservice/publify/blob/d8df2bf923a2faf5fab1e18495573fffb926c2a3/app/models/comment.rb#L16) so I've specified the `unapproved` scope instead.

Use correct query string param in dashboard links

---

app/controllers/accounts_controller.rb
app/controllers/admin/base_controller.rb
app/controllers/admin/notes_controller.rb
app/controllers/admin/pages_controller.rb
app/controllers/admin/seo_controller.rb
app/controllers/application_controller.rb
app/controllers/articles_controller.rb
app/controllers/comments_controller.rb
app/controllers/content_controller.rb
app/controllers/feedback_controller.rb
app/controllers/notes_controller.rb
app/controllers/setup_controller.rb
app/controllers/tags_controller.rb

_action methods became preferred to _filter methods in Rails 4.2, so this is a straightforward replacement.

_action methods became preferred to _filter methods in Rails 4.2.

---

app/views/admin/users/edit.html.erb

The action was set to "edit," causing attempts to update/edit users to fail.  Changing to "update" used the "update" method in the users_controller.rb rather than the edit method, resolving the issue.

Changed the "edit" action to "update" action

---

app/views/admin/pages/_pages.html.erb
app/views/admin/pages/index.html.erb
app/views/admin/tags/new.html.erb

I removed the articles column in adnin/tags/new and the permanent link column in admin/pages. 
Issues: #449 #451

Removed useless information in admin/tags/new and admin/pages 

---

app/assets/javascripts/administration_jquery.js

The dropdown menus on the admin pages were not dropping. This fixes it. If you can't replicate the problem, feel free to ignore this request. But perhaps it will help others.
publify/publify#604

Fix admin dropdown menu

---

app/controllers/admin/redirects_controller.rb
app/models/content.rb
app/models/note.rb
app/models/redirect.rb
app/views/notes/_note.html.erb
db/migrate/20150807134129_simplify_redirect_relations.rb
db/schema.rb
spec/controllers/admin/content_controller_spec.rb
spec/controllers/admin/pages_controller_spec.rb
spec/controllers/admin/redirects_controller_spec.rb
spec/models/article_spec.rb
spec/models/content_spec.rb
spec/models/note_spec.rb
spec/models/page_spec.rb

Changes the relation between redirects and content so that each content has (at most) only one redirect, and each redirect has (at most) only one contents. This makes sense for two reasons:
* The code in Content already enforced only one redirect to exist.
* There is no code assigning additional content to a redirect, nor is there any logical reason to want to do so.
This PR also fixes the feature where content-related redirects are hidden from the redirect editor. This makes sense because we do not want to allow editing the target URL for such redirects.

Simplify redirects

---

app/views/devise/mailer/reset_password_instructions.html.erb

removing a parenthesis that caused the most error

removing a parenthesis that caused the most error

---

CHANGELOG.md
app/views/layouts/accounts.html.erb
app/views/layouts/administration.html.erb
app/views/layouts/editor.html.erb

I had random issues under dev mode because javascript loaded admin js libraries without order, because under development mode js libraries are not bundled into one file.

Load JavaScript asynchronously only in production

---

app/models/comment.rb
app/models/feedback.rb

Got this error on `/admin/feedback?only=ham`:
```
PG::AmbiguousColumn: ERROR:  column reference "state" is ambiguous
LINE 1: ...IN ('Article') AND "contents"."blog_id" = $1 AND (state in (...
^
: SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "feedback" INNER JOIN "contents" ON "feedback"."article_id" = "contents"."id" WHERE "contents"."type" IN ('Article') AND "contents"."blog_id" = $1 AND (state in ('presumed_ham', 'ham')) LIMIT 20 OFFSET 0) 
```

using AR's IN syntax to avoid ambiguous reference

---

config/locales/pt-BR.yml
config/locales/sidebars.pt-BR.yml

Some lines on `config/locales/pt-BR.yml` and `config/locales/sidebar-pt.BR.yml` were missing the translation for portuguese or could be improved.

Portuguese translation

---

publify_core/app/assets/javascripts/spinnable.js
publify_core/app/views/admin/content/index.js.erb

Hide spinner on ajax complete

---

db/migrate/20170528093428_move_resources_to_content.publify_core_engine.rb
db/migrate/20170528120220_move_tags_to_content.publify_core_engine.rb
db/schema.rb
publify_amazon_sidebar/spec/dummy/db/migrate/20170528164251_move_resources_to_content.publify_core_engine.rb
publify_amazon_sidebar/spec/dummy/db/migrate/20170528164439_move_tags_to_content.publify_core_engine.rb
publify_amazon_sidebar/spec/dummy/db/schema.rb
publify_core/app/controllers/articles_controller.rb
publify_core/app/controllers/tags_controller.rb
publify_core/app/controllers/xml_controller.rb
publify_core/app/helpers/xml_helper.rb
publify_core/app/models/article.rb
publify_core/app/models/content.rb
publify_core/app/models/resource.rb
publify_core/app/models/tag.rb
publify_core/app/views/admin/tags/_index_and_form.html.erb
publify_core/db/migrate/20170528093024_move_resources_to_content.rb
publify_core/db/migrate/20170528094923_move_tags_to_content.rb
publify_core/spec/controllers/admin/content_controller_spec.rb
publify_core/spec/controllers/tags_controller_spec.rb
publify_core/spec/dummy/db/schema.rb
publify_core/spec/models/article_spec.rb
publify_core/spec/models/tag_spec.rb
publify_textfilter_code/spec/dummy/db/migrate/20170528164322_move_resources_to_content.publify_core_engine.rb
publify_textfilter_code/spec/dummy/db/migrate/20170528164423_move_tags_to_content.publify_core_engine.rb
publify_textfilter_code/spec/dummy/db/schema.rb

By moving some relations to the Content superclass, we can preload all relations needed in the articles index.

Refactor articles index

---

MIT-LICENSE
README.md

For #709 and (part of #714).
I've decided to keep the stuff in the license file short, but list relevant individuals in the README (basically using all the names that were at some point in the MAINTAINERS file).
/cc @fdv, @yaf, @ook, @shingara, @pdcawley, @tobi.

Update copyright information and contributor list

---

publify_core/app/controllers/tags_controller.rb
publify_core/spec/controllers/articles_controller_spec.rb
publify_core/spec/controllers/tags_controller_spec.rb
publify_core/spec/factories.rb

Ensures:
- page title has no extra white space
- description is not empty and uses correct template
Fixes #305.

Correctly set tag page title and description

---

publify_core/app/models/article.rb
publify_core/app/views/articles/read.html.erb
publify_core/config/locales/da.yml
publify_core/config/locales/de.yml
publify_core/config/locales/en.yml
publify_core/config/locales/es-MX.yml
publify_core/config/locales/fr.yml
publify_core/config/locales/he.yml
publify_core/config/locales/it.yml
publify_core/config/locales/ja.yml
publify_core/config/locales/lt.yml
publify_core/config/locales/nb-NO.yml
publify_core/config/locales/nl.yml
publify_core/config/locales/pl.yml
publify_core/config/locales/pt-BR.yml
publify_core/config/locales/ro.yml
publify_core/config/locales/ru.yml
publify_core/config/locales/zh-CN.yml
publify_core/config/locales/zh-TW.yml

This mainly avoids web clients following the trackback link, which only supports post requests.

Clean up feedback urls

---

publify_core/Manifest.txt
publify_core/app/controllers/theme_controller.rb
publify_core/config/routes.rb
publify_core/spec/controllers/theme_controller_spec.rb

To be consistent, update `ThemeController` action `javascript` to `javascripts`.
Skip CSRF protection for action `javascripts` so that js via Get request loaded successfully.
Related Rails Issue: https://github.com/rails/rails/pull/13345

Fix theme javascripts action

---

Gemfile
README.md

This updates the instructions for deploying Publify to Heroku.
Highlights:
* Drop Heroku-specific Gemfile section and its environment variable, in favor of telling users how to edit it. They would have to adjust the Ruby version anyway, so there's really no point.
* Make all environment variables capitalized
* Add instructions for adding a Procfile based on puma
Fixes #832. Fixes #842.

Update Heroku instructions

---

config/locales/en.yml
config/locales/pl.yml
lib/tasks/i18n.rake
publify_core/Rakefile

All tasks can be run now always now that support for Ruby 2.2 has been dropped.

Always run full I18n tasks health check

---

publify_core/app/models/trackback.rb

No new Trackback objects should be stored in the database, and also no tests fail when this code is removed.

Remove superfluous initializer from Trackback

---

publify_core/app/controllers/comments_controller.rb
publify_core/app/views/articles/_comment_preview.html.erb
publify_core/spec/controllers/comments_controller_spec.rb

Comment preview is broken because the partial can't render the comment body. This fixes that by linking the article so the needed text filter can be found.

Fix comment preview

---

CHANGELOG.md
publify_core/CHANGELOG.md
publify_core/app/controllers/text_controller.rb
publify_core/app/views/admin/seo/_general.html.erb
publify_core/app/views/shared/_page_header.html.erb
publify_core/config/locales/da.yml
publify_core/config/locales/de.yml
publify_core/config/locales/en.yml
publify_core/config/locales/es-MX.yml
publify_core/config/locales/fr.yml
publify_core/config/locales/he.yml
publify_core/config/locales/it.yml
publify_core/config/locales/ja.yml
publify_core/config/locales/lt.yml
publify_core/config/locales/nb-NO.yml
publify_core/config/locales/nl.yml
publify_core/config/locales/pl.yml
publify_core/config/locales/pt-BR.yml
publify_core/config/locales/ro.yml
publify_core/config/locales/ru.yml
publify_core/config/locales/zh-CN.yml
publify_core/config/locales/zh-TW.yml
publify_core/config/routes.rb
publify_core/spec/controllers/text_controller_spec.rb

The existing implementation was buggy:
- Links incorrectly used a relative URL
- Links abused rel='author'; We have another page for the author of a post.
- The provided route was incorrect when Publify is used in a sub-URI.
- The provided default was bad
In addition, the humans.txt concept does not seem to be a big hit. Users who want to provide a humans.txt file should just add one to their web server root manually.
Fixes #901.

Drop support for generating humans.txt

---

Gemfile

The dummy application won't activate with sqlite3 version 1.4.

Ensure correct version of sqlite3 is loaded

---

.travis.yml
lib/tasks/i18n.rake
lib/tasks/manifests.rake

Should speed up the build by linting only once instead of 9 times.
Concretely:
* Move lint task to a separate build stage

Introduce Travis stages

---

publify_core/publify_core.gemspec

See https://nvd.nist.gov/vuln/detail/CVE-2019-13574.

Require mini_magick version with fix for CVE-2019-13574

---

publify_core/app/views/devise/registrations/new.html.erb

This silences a deprecation warning about `#devise_error_messages`.

Use new way to render Devise error messages in view override

---

publify_amazon_sidebar/.gitrepo
publify_amazon_sidebar/Rakefile
publify_core/.gitrepo
publify_core/Rakefile
publify_textfilter_code/.gitrepo
publify_textfilter_code/Rakefile

Uses [git-subrepo](https://github.com/ingydotnet/git-subrepo) to break out engines into their own repositories. From here on, development can occur either in the subrepos or this main repo.

Push engines into subrepos

---

Gemfile
publify_core/app/uploaders/resource_uploader.rb
publify_core/publify_core.gemspec

- Bump Rails version to one that includes transitive dependency on marcel 1.0.0
- Replace mimemagic dependency with dependency on marcel 1.0.0
- Update code that used MimeMagic to use Marcel::MimeType
- Remove old unused helper method

Replace mimemagic with marcel

---

Gemfile
lib/publify_textfilters.rb
publify_core/lib/sidebar_registry.rb
publify_core/spec/helpers/base_helper_spec.rb
publify_core/spec/lib/publify_time_spec.rb
publify_core/spec/models/article_spec.rb

- Update rubocop to version 1.14.0
- Update rubocop-performance to version 1.11.3
- Update rubocop-rails to version 2.10.1
- Update rubocop-rspec to version 2.3.0
- Autocorrect Style/StringLiterals
- Fix Rails/TimeZoneAssignment offenses

Update rubocop gems and fix new offenses

---

publify_core/lib/publify_textfilter_markdown.rb
publify_textfilter_code/lib/publify_app/textfilter_code.rb
publify_textfilter_code/spec/lib/publify_app/textfilter_code_spec.rb

This removes the wrapping of code blocks in 'notextile' tags that was used to keep the textile filter from interpreting the code in the block as textile markup.
Fixes #811.

Remove use of 'notextile'

---

publify_core/app/controllers/admin/themes_controller.rb
publify_core/app/models/text_filter.rb
publify_core/spec/lib/publify_textfilter_twitterfilter_spec.rb
publify_textfilter_code/spec/lib/publify_app/textfilter_code_spec.rb
spec/models/text_filter_spec.rb

This makes the translation from TextFilter instance to a set of TextFilterPlugin classes internal to the TextFilter class, allowing more flexibility.

Remove TextFilter.filter_text in favor of #filter_text

---

publify_core/app/views/admin/feedback/article.html.erb
publify_core/app/views/admin/feedback/index.html.erb
publify_core/config/locales/da.yml
publify_core/config/locales/de.yml
publify_core/config/locales/en.yml
publify_core/config/locales/es-MX.yml
publify_core/config/locales/fr.yml
publify_core/config/locales/he.yml
publify_core/config/locales/it.yml
publify_core/config/locales/ja.yml
publify_core/config/locales/lt.yml
publify_core/config/locales/nb.yml
publify_core/config/locales/nl.yml
publify_core/config/locales/pl.yml
publify_core/config/locales/pt-BR.yml
publify_core/config/locales/ro.yml
publify_core/config/locales/ru.yml
publify_core/config/locales/zh-CN.yml
publify_core/config/locales/zh-TW.yml

- Hide bulk ops when not relevant
- Unify table headings
- Show bulk ops and select-all check only once in main feedback index page

Improve feedback listings

---

publify_core/app/models/content_base.rb
publify_core/app/models/note.rb
publify_core/lib/publify_textfilter_twitterfilter.rb
publify_core/spec/lib/publify_textfilter_twitterfilter_spec.rb
publify_core/spec/models/note_spec.rb
publify_core/spec/models/text_filter_spec.rb

- Test full HTML generation for Note instead of internal method result
- Move application of Twitterfilter to postprocess stage
- Make TextFilter#help test pass whether macro filters are present or not
- Make autolinking in notes not break markdown links
Fixes #254.

Handle markdown links in notes correctly

---

publify_core/lib/publify_textfilter_twitterfilter.rb
publify_core/publify_core.gemspec
publify_core/spec/lib/publify_textfilter_twitterfilter_spec.rb
publify_core/spec/models/note_spec.rb

- Add specs for more complex Notes markup cases
- Replace `@mention` handling with a robust solution
- Replace `#hashtag` handling with a robust solution

Make notes twitterfilter robust

---

.github/workflows/ruby.yml
Gemfile
README.md

This forces Publify users to upgrade nokogiri to at least version 1.12.5, to avoid security issue CVE-2021-41098.

Force minimum nokogiri version to avoid security issues

---

.rubocop.yml
Gemfile
publify_amazon_sidebar/.rubocop.yml
publify_amazon_sidebar/publify_amazon_sidebar.gemspec
publify_core/.rubocop.yml
publify_core/lib/spam_protection.rb
publify_core/publify_core.gemspec
publify_core/spec/helpers/base_helper_spec.rb
publify_textfilter_code/.rubocop.yml
publify_textfilter_code/lib/publify_app/textfilter_code.rb
publify_textfilter_code/publify_textfilter_code.gemspec

- Move explicit Nokogiri version specification to publify_core gem
- Bump required_ruby_version for engine gems

Move nokogiri dependency to gem

---

.rubocop.yml
Gemfile
app/models/authors_sidebar.rb
lib/publify_avatar_gravatar.rb
publify_core/app/controllers/articles_controller.rb
publify_core/app/helpers/base_helper.rb
publify_core/app/models/meta_sidebar.rb
publify_core/app/models/static_sidebar.rb
publify_core/lib/publify_core/testing_support/factories/sequences.rb
publify_core/lib/publify_textfilter_markdown.rb
publify_core/lib/publify_textfilter_markdown_smartquotes.rb
publify_core/spec/controllers/admin/feedback_controller_spec.rb
publify_core/spec/controllers/admin/settings_controller_spec.rb
publify_core/spec/helpers/base_helper_spec.rb
publify_core/spec/lib/publify_textfilter_twitterfilter_spec.rb
publify_core/spec/lib/publify_time_spec.rb
publify_core/spec/lib/transforms_spec.rb
publify_core/spec/models/article_spec.rb
publify_core/spec/models/configuration_spec.rb
publify_core/spec/models/note_spec.rb
publify_core/spec/views/articles/index_atom_feed_spec.rb
publify_core/spec/views/articles/index_rss_feed_spec.rb
publify_core/spec/views/feedback/index.atom.builder_spec.rb
publify_core/spec/views/feedback/index.rss.builder_spec.rb

- Update rubocop to version 1.22.3
- Update rubocop-performance to version 1.12.0
- Update rubocop-rails to version 2.12.4
- Update rubocop-rspec to version 2.6.0
- Autocorrect Layout/LineEndStringConcatenationIndentation
- Autocorrect Security/IoMethods
- Update cop namespace for Capybara/FeatureMethods
- Correct RSpec/ExcessiveDocstringSpacing
- Autocorrect Rails/ContentTag
- Autocorrect Style/QuotedSymbols
- Autocorrect Style/StringLiterals
- Fix sequence expression
- Correct Rails/I18nLocaleAssignment offense
- Wrap long lines

Update RuboCop dependencies and fix new offenses

---

publify_core/app/controllers/admin/content_controller.rb
publify_core/spec/controllers/admin/content_controller_spec.rb

The password field was present in the form, but not accepted by the controller. This change adds password to the list of accepted fields.

Fix setting the article password from the Admin

---

Gemfile

This forces users of Publify to upgrade to a version of puma and rails where CVE-2022-23633 has been fixed.
Before this patch lands, users can already upgrade puma and rails independently.
See also https://github.com/advisories/GHSA-wh98-p28r-vrc9

Bump mimimum puma and Rails versions

---

publify_core/app/controllers/admin/content_controller.rb
publify_core/app/controllers/comments_controller.rb
publify_core/app/models/article.rb
publify_core/app/models/comment.rb
publify_core/lib/spam_protection.rb
publify_core/spec/controllers/admin/content_controller_spec.rb
publify_core/spec/controllers/comments_controller_spec.rb
publify_core/spec/models/article_spec.rb

When an article is not published, `CommentsController#create` should not allow creation of comments.
- Assign comment to current user if logged in
- Improve spec structure in `Admin::ContentController` specs
- Improve specs for `Article#pings_closed?`
- Use around blocks to switch time zones in article specs
- Restructure specs for `CommentsController#create`
- Do not allow comments on `Article` if not published
- Disallow pings if `Article` is not published
- Replace pointless use of `protected` with `private`

Disallow comments on draft articles

---

publify_core/app/models/feedback.rb
publify_core/spec/models/comment_spec.rb

Images in comments cause information leaks. Disallow them.
- Unify specs for disallowing script tags in comments
- Do not allow images in comments

Disallow images in comments

---

publify_core/.rubocop.yml
publify_core/.rubocop_todo.yml
publify_core/app/views/devise/mailer/reset_password_instructions.html.erb
publify_core/app/views/devise/passwords/edit.html.erb
publify_core/app/views/devise/passwords/new.html.erb
publify_core/spec/features/reset_password_spec.rb

- Silence Devise warnings about deprecated `devise_error_messages!` method
- Fix error in password reset mail
- Allow feature specs to use feature spec methods
Fixes #1053.

Fix password reset process

---

publify_core/app/views/articles/search.html.erb
publify_core/spec/controllers/articles_controller_spec.rb

Hide bodies of password-protected articles in search results

---

publify_core/app/views/admin/feedback/article.html.erb
publify_core/app/views/admin/feedback/index.html.erb
publify_core/spec/controllers/admin/feedback_controller_spec.rb

Using `#hidden_field` creates a field for `article_id[article.id]` instead of `article_id`.
Fixes #898.

Provide correct article_id input in bulkops form

---

publify_core/app/controllers/articles_controller.rb
publify_core/spec/controllers/articles_controller_spec.rb
spec/controllers/articles_controller_spec.rb

This fixes an issue where the password-protected article text is actually included in a meta tag.

Do not create article meta description for password-protected articles

---

config/locales/ar.yml
config/locales/sidebars.ar.yml
db/schema.rb
publify_core/Manifest.txt
publify_core/app/assets/javascripts/lang/ar_AR.js
publify_core/config/locales/ar.yml
publify_core/config/locales/da.yml
publify_core/config/locales/de.yml
publify_core/config/locales/en.yml
publify_core/config/locales/es-MX.yml
publify_core/config/locales/fr.yml
publify_core/config/locales/he.yml
publify_core/config/locales/it.yml
publify_core/config/locales/ja.yml
publify_core/config/locales/lt.yml
publify_core/config/locales/nb.yml
publify_core/config/locales/nl.yml
publify_core/config/locales/pl.yml
publify_core/config/locales/pt-BR.yml
publify_core/config/locales/ro.yml
publify_core/config/locales/ru.yml
publify_core/config/locales/sidebars.ar.yml
publify_core/config/locales/zh-CN.yml
publify_core/config/locales/zh-TW.yml
publify_core/lib/publify_core/lang.rb

- Add 5 files for ar localization at ( /config/locales/ar.yml, /config/locales/sidebars.ar.yml, /publify_core/config/locales/ar.yml,  /publify_core/config/locales/sidebars.ar.yml, and /publify_core/app/assets/javascripts/lang/ar_AR.js).
- Update project's locales files, to support the new language.
- Update /publify_core/lib/publify_core/lang.rb file.
- Finally, testing the project with the ar localization, and everything is good with arabic localization.

Add arabic language to the project

---

publify_core/app/controllers/admin/content_controller.rb
publify_core/spec/controllers/admin/content_controller_spec.rb

- Use only the main id parameter to find Article to update
- Only allow publisher to autosave their own articles

Fix admin article access control

---

CHANGELOG.md
publify_amazon_sidebar/CHANGELOG.md
publify_amazon_sidebar/lib/publify_amazon_sidebar/version.rb
publify_amazon_sidebar/publify_amazon_sidebar.gemspec
publify_core/CHANGELOG.md
publify_core/app/controllers/admin/articles_controller.rb
publify_core/app/uploaders/resource_uploader.rb
publify_core/lib/publify_core/version.rb
publify_core/spec/controllers/admin/articles_controller_spec.rb
publify_core/spec/controllers/admin/resources_controller_spec.rb
publify_textfilter_code/CHANGELOG.md
publify_textfilter_code/lib/publify_textfilter_code/version.rb
publify_textfilter_code/publify_textfilter_code.gemspec

- Use only the main id parameter to find Article to update
- Only allow publisher to autosave their own articles
- Refuse html files as resources even if declared to be plain text
- Prepare version 9.2.9 for release

Pull in latest changes from 9-2-stable

---

Gemfile
publify_core/app/models/blog.rb
publify_core/app/models/config_manager.rb
publify_core/publify_core.gemspec
publify_core/spec/lib/theme_spec.rb
publify_core/spec/models/blog_spec.rb
publify_core/spec/models/user_spec.rb
publify_core/spec/rails_helper.rb

- Limit allowed setting types
- Add shoulda-matchers for testing validations
- Move engine_root spec helper method to a let definition
- Maximize string settings at 256 characters

Limit length of settings values

---

publify_core/app/models/user.rb
publify_core/spec/models/user_spec.rb

- Clean up user validation specs
- Require login to stay unique when updating a User
- Spec that email uniqueness is already guaranteed by Devise

Require login to stay unique when updating a user

---

publify_core/Manifest.txt
publify_core/app/models/blog.rb
publify_core/app/models/comment.rb
publify_core/app/models/concerns/string_length_limit.rb
publify_core/app/models/config_manager.rb
publify_core/app/models/content.rb
publify_core/app/models/feedback.rb
publify_core/app/models/ping.rb
publify_core/app/models/post_type.rb
publify_core/app/models/redirect.rb
publify_core/app/models/resource.rb
publify_core/app/models/tag.rb
publify_core/app/models/trackback.rb
publify_core/app/models/user.rb
publify_core/spec/models/blog_spec.rb
publify_core/spec/models/comment_spec.rb
publify_core/spec/models/content_spec.rb
publify_core/spec/models/feedback_spec.rb
publify_core/spec/models/ping_spec.rb
publify_core/spec/models/post_type_spec.rb
publify_core/spec/models/redirect_spec.rb
publify_core/spec/models/resource_spec.rb
publify_core/spec/models/tag_spec.rb
publify_core/spec/models/trackback_spec.rb
publify_core/spec/models/user_spec.rb

- Use preferred method of taking action when ConfigManager is included
- Refactor Feedback validations
- Validate lengths of string attributes
- Validate length of user's name attribute

Validate lengths of string attributes

---

.rubocop.yml
Gemfile
publify_amazon_sidebar/.rubocop.yml
publify_amazon_sidebar/publify_amazon_sidebar.gemspec
publify_core/.rubocop.yml
publify_core/app/helpers/base_helper.rb
publify_core/publify_core.gemspec
publify_core/spec/lib/theme_spec.rb
publify_core/spec/models/article_spec.rb
publify_textfilter_code/.rubocop.yml
publify_textfilter_code/publify_textfilter_code.gemspec
publify_textfilter_code/spec/lib/publify_app/textfilter_code_spec.rb
spec/lib/publify_textfilter_flickr_spec.rb

- Update rubocop to version 1.35.0
- Configure Layout/LineContinuationLeadingSpace and fix related offenses
- Fix Style/FileRead offense
- Correct Gemspec/RequireMFA offenses
- Fix Style/OpenStructUse offenses

Update RuboCop and fix new offenses

---

Gemfile
publify_core/.rubocop.yml
publify_core/spec/controllers/admin/dashboard_controller_spec.rb
publify_core/spec/helpers/author_helper_spec.rb
publify_core/spec/models/blog_spec.rb
publify_core/spec/models/configuration_spec.rb
publify_core/spec/models/user_spec.rb

- Update rubocop-rspec to version 2.12.1
- Fix cop namespace for Capybara/FeatureMethods
- Autocorrect RSpec/BeEq
- Replace `have_selector` with more specific `have_link` where possible

Update rubocop-rspec and fix new offenses

---

db/migrate/20221007091118_remove_table_sitealizer.publify_core_engine.rb
db/schema.rb
publify_amazon_sidebar/spec/dummy/db/migrate/20221007091137_remove_table_sitealizer.publify_core_engine.rb
publify_amazon_sidebar/spec/dummy/db/schema.rb
publify_core/Manifest.txt
publify_core/db/migrate/20221007091049_remove_table_sitealizer.rb
publify_core/spec/dummy/db/schema.rb
publify_textfilter_code/spec/dummy/db/migrate/20221007091208_remove_table_sitealizer.publify_core_engine.rb
publify_textfilter_code/spec/dummy/db/schema.rb

Remove sitealizer table
Issue - https://github.com/publify/publify/issues/1076

remove sitealizer table

---

spec/controllers/articles_controller_spec.rb
themes/bootstrap-2/views/articles/search.html.erb

- Fix rendering of article body in search results
- Test themes' search results rendering more thoroughly
- Hide protected article text from search result in bootstrap-2 theme
- Set theme when creating blog in ArticlesController specs

Fix article search rendering

---

.rubocop.yml
Gemfile
spec/controllers/articles_controller_spec.rb
spec/views/comments/html_sanitization_spec.rb
spec/views/layouts/default_spec.rb

- Control rubocop-capybara version explicitly
- Autocorrect Capybara/RSpec/HaveSelector offenses
- Disable Capybara/ClickLinkOrButtonStyle cop

Handle new rubocop-capybara offenses

---

lib/publify_textfilter_flickr.rb
lib/publify_textfilter_lightbox.rb
spec/lib/text_filter_plugin_spec.rb

MacroPre is now a module that must be included.

Update text filters to work with the changed text filter plugin system

---

.github/workflows/ruby.yml
.rubocop.yml
spec/rails_helper.rb

- Drop support for Ruby 2.7
- Build with Rubies 3.0 through 3.3 in CI

Support Ruby 3.0 and up

---

.github/workflows/ruby.yml
Gemfile
bin/cucumber
bin/i18n-tasks
bin/rails
config/application.rb
lib/tasks/i18n.rake

Rails before 7.1 needs logger to be pre-loaded. Also fixes an issue with migrations whose root cause is unclear.

Fix build failure by requiring logger explictly

---

.github/workflows/ruby.yml

Setting RAILS_ENV is not needed.
This reverts commit 5c3d95411dc96c2c6ae32e8371087460e6e1a91c.

Remove unneeded env var from GitHub Actions
