publify/publify

- app/models/text_filter.rb
- app/views/articles/read.html.erb
- spec/controllers/articles_controller_spec.rb
- spec/factories.rb
- themes/bootstrap-2/views/articles/read.html.erb
Articles with trackbacks gave a 500.
> Fix rendering for article with feedback

- spec/models/article_spec.rb
Attempts to finally fix the very annoying intermittent spec failures.
> Fix article pinger spec

- app/views/admin/settings/display.html.erb
admin/settings/display -> changes the date and time radio buttons to dropdown menus.
Issue: #458
> Dropdown menu

- CONTRIBUTING.md
Starts the first part of #503 but does not include list of contributors.
Hope you don't mind this start on the file.
> Add CONTRIBUTING to guide fixing issues or reporting bugs

- app/models/article.rb
- app/models/comment.rb
- app/models/note.rb
- app/models/page.rb
- app/models/post_type.rb
- app/models/profile.rb
- app/models/redirect.rb
- app/models/tag.rb
- app/models/trackback.rb
- app/models/user.rb
The preferred validation style seems to have changed. This changes old style to new style.
> Update validation clauses to new style

- app/assets/javascripts/sidebar.js
- app/controllers/admin/sidebar_controller.rb
- config/routes.rb
- lib/sidebar.rb
> Fix sidebar

- app/assets/stylesheets/publify_admin.css.scss
less clickthroughs for users; better UX
> changed navbar to dropdown onhover

- app/views/admin/pages/_pages.html.erb
In response to https://github.com/publify/publify/issues/630
> Changed the page permalink to show and not edit

- themes/bootstrap-2/views/layouts/default.html.erb
> Fix broken stylesheet link in bootstrap2 theme

- app/models/feedback.rb
Since akismet gem was updated from 1.0 to 2.0 in Gemfile, it should be updated akismet api in feedback.rb. So, I changed akismet method names and params names.
> Update akismet api in feedback.rb

- db/seeds.rb
When I try to execute db:seed, it has error of NOT NULL constraint for SideBar related model.
So I added temporary value of blog_id attribute.
> Fixed rake db:seed error

- app/controllers/application_controller.rb
> Remove ancient #reset_local_cache method

- app/views/admin/cache/show.html.erb
- app/views/admin/content/_form.html.erb
- config/locales/da.yml
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es-MX.yml
- config/locales/fr.yml
- config/locales/he.yml
- config/locales/it.yml
- config/locales/ja.yml
- config/locales/lt.yml
- config/locales/nb-NO.yml
- config/locales/nl.yml
- config/locales/pl.yml
- config/locales/pt-BR.yml
- config/locales/ro.yml
- config/locales/ru.yml
- config/locales/zh-CN.yml
- config/locales/zh-TW.yml
> Fix spelling of 'explanation'

- app/controllers/admin/profiles_controller.rb
- app/controllers/admin/users_controller.rb
- app/helpers/admin/feedback_helper.rb
- app/models/ability.rb
- app/models/profile.rb
- app/models/user.rb
- app/views/admin/users/_form.html.erb
- app/views/admin/users/index.html.erb
- db/migrate/20160605103918_replace_profile_id_with_string.rb
- db/migrate/20160605154632_remove_profiles.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/admin/content_controller_spec.rb
- spec/controllers/admin/dashboard_controller_spec.rb
- spec/controllers/admin/feedback_controller_spec.rb
- spec/controllers/admin/profiles_controller_spec.rb
- spec/controllers/admin/redirects_controller_spec.rb
- spec/controllers/admin/resources_controller_spec.rb
- spec/controllers/admin/sidebar_controller_spec.rb
- spec/controllers/admin/tags_controller_spec.rb
- spec/controllers/admin/textfilters_controller_spec.rb
- spec/controllers/admin/themes_controller_spec.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/controllers/articles_controller_spec.rb
- spec/factories.rb
- spec/models/article_spec.rb
- spec/models/user_spec.rb
> Remove Profile model

- CHANGELOG.md
- app/controllers/admin/sidebar_controller.rb
- app/controllers/application_controller.rb
- app/controllers/content_controller.rb
- app/helpers/application_helper.rb
- lib/sidebar.rb
- lib/sidebar_field.rb
- spec/controllers/admin/sidebar_controller_spec.rb
Fixes #704 and cleans up some code.
> Clean up and fix sidebar

- app/controllers/admin/users_controller.rb
- app/helpers/admin/base_helper.rb
- app/views/admin/users/_form.html.erb
- spec/controllers/admin/users_controller_spec.rb
> Fix user update

- app/views/articles/archives.html.erb
- app/views/shared/_page_header.html.erb
- lib/publify_avatar_gravatar.rb
- spec/controllers/articles_controller_spec.rb
- spec/lib/publify_avatar_gravatar_spec.rb
- spec/views/shared/_page_header_spec.rb
> Fix more html escaping

- app/models/article/factory.rb
- spec/models/article/factory_spec.rb
> Build new article instead of attempting creation

- app/models/article.rb
- app/models/comment.rb
- app/models/feedback.rb
- spec/factories.rb
- spec/models/article_spec.rb
> Improve published feedback, comments and trackbacks collections

- app/assets/javascripts/publify_admin.js
- app/assets/javascripts/publify_jquery.js
- app/controllers/admin/base_controller.rb
- app/controllers/admin/content_controller.rb
- app/controllers/admin/notes_controller.rb
- app/views/admin/notes/_form.html.erb
> Fix note publication date

- app/controllers/admin/dashboard_controller.rb
- spec/controllers/admin/feedback_controller_spec.rb
> Replace deprecated count condition syntax

- publify_core/app/views/articles/feedback_atom_feed.atom.builder
- publify_core/app/views/articles/feedback_rss_feed.rss.builder
- publify_core/spec/rails_helper.rb
- publify_core/spec/views/articles/feedback_atom_feed_spec.rb
- publify_core/spec/views/articles/feedback_rss_feed_spec.rb
Fixes https://github.com/publify/publify_core/issues/30 and https://github.com/publify/publify_core/issues/29.
> Fix links in feeds

- publify_core/app/models/article.rb
- publify_core/app/views/articles/_archives_article.html.erb
- publify_core/app/views/articles/archives.html.erb
- publify_core/app/views/authors/show.html.erb
- publify_core/config/locales/da.yml
- publify_core/config/locales/de.yml
- publify_core/config/locales/en.yml
- publify_core/config/locales/es-MX.yml
- publify_core/config/locales/fr.yml
- publify_core/config/locales/he.yml
- publify_core/config/locales/it.yml
- publify_core/config/locales/ja.yml
- publify_core/config/locales/lt.yml
- publify_core/config/locales/nb-NO.yml
- publify_core/config/locales/nl.yml
- publify_core/config/locales/pl.yml
- publify_core/config/locales/pt-BR.yml
- publify_core/config/locales/ro.yml
- publify_core/config/locales/ru.yml
- publify_core/config/locales/zh-CN.yml
- publify_core/config/locales/zh-TW.yml
- publify_core/spec/controllers/articles_controller_spec.rb
> Cache archives page

- publify_core/app/views/articles/index_atom_feed.atom.builder
- publify_core/app/views/authors/show_atom_feed.atom.builder
- publify_core/app/views/feedback/index.atom.builder
- publify_core/spec/views/articles/index_atom_feed_spec.rb
- publify_core/spec/views/authors/show_atom_feed_spec.rb
- publify_core/spec/views/feedback/index.atom.builder_spec.rb
https://github.com/publify/publify_core/issues/29
> Fix other atom feeds

- db/migrate/20170702105518_remove_published_at_from_feedback.publify_core_engine.rb
- db/schema.rb
- publify_amazon_sidebar/spec/dummy/db/migrate/20170702105825_remove_published_at_from_feedback.publify_core_engine.rb
- publify_amazon_sidebar/spec/dummy/db/schema.rb
- publify_core/CHANGELOG.md
- publify_core/Manifest.txt
- publify_core/Rakefile
- publify_core/app/controllers/admin/dashboard_controller.rb
- publify_core/app/controllers/feedback_controller.rb
- publify_core/app/models/feedback.rb
- publify_core/db/migrate/20170702105201_remove_published_at_from_feedback.rb
- publify_core/spec/controllers/articles_controller_spec.rb
- publify_core/spec/controllers/feedback_controller_spec.rb
- publify_core/spec/dummy/db/schema.rb
- publify_core/spec/factories.rb
- publify_core/spec/models/article_spec.rb
- publify_core/spec/models/comment_spec.rb
- publify_core/spec/models/feedback_spec.rb
- publify_textfilter_code/spec/dummy/db/migrate/20170702105845_remove_published_at_from_feedback.publify_core_engine.rb
- publify_textfilter_code/spec/dummy/db/schema.rb
> Fix feed order

- publify_core/app/views/admin/seo/_general.html.erb
- publify_core/app/views/admin/seo/_permalinks.html.erb
- publify_core/app/views/admin/seo/_titles.html.erb
- publify_core/app/views/admin/settings/display.html.erb
- publify_core/app/views/admin/settings/feedback.html.erb
- publify_core/app/views/admin/settings/index.html.erb
- publify_core/app/views/admin/settings/write.html.erb
Fixes the display of certain check boxes in the settings forms, and in addition improves the forms' responsiveness.
Fixes #804.
> Fix settings forms

- publify_core/CHANGELOG.md
- publify_core/app/helpers/authors_helper.rb
- publify_core/app/models/blog.rb
- publify_core/app/models/content.rb
- publify_core/app/views/articles/feedback_rss_feed.rss.builder
- publify_core/app/views/articles/index_rss_feed.rss.builder
- publify_core/app/views/authors/show_rss_feed.rss.builder
- publify_core/app/views/feedback/index.rss.builder
- publify_core/app/views/shared/_atom_item_article.atom.builder
- publify_core/app/views/shared/_rss_item_article.rss.builder
- publify_core/spec/factories.rb
- publify_core/spec/helpers/author_helper_spec.rb
- publify_core/spec/models/configuration_spec.rb
- publify_core/spec/models/content_spec.rb
- publify_core/spec/views/articles/index_rss_feed_spec.rb
- spec/factories.rb
Fixes #279. Also improves RSS feed.
> Remove link_to_author setting

- Gemfile
- config/application.rb
- publify_core/app/controllers/base_controller.rb
- publify_core/lib/publify_core/engine.rb
- publify_core/spec/features/signup_spec.rb
> Fix sign up

- config/locales/pl.yml
- config/locales/sidebars.pl.yml
- publify_core/config/locales/pl.yml
Part of https://github.com/publify/publify/issues/803
> Add Polish translations

- publify_core/app/controllers/admin/pages_controller.rb
- publify_core/app/controllers/admin/profiles_controller.rb
- publify_core/app/controllers/admin/users_controller.rb
- publify_core/app/views/admin/content/_form.html.erb
- publify_core/app/views/admin/pages/_form.html.erb
- publify_core/app/views/articles/view_page.html.erb
- themes/bootstrap-2/views/articles/view_page.html.erb
I thought I could quickly set up a new blog after my old Typo blog went down to /dev/nul.
Unfortunately Publify 9.0.1, 9.0.0 and 8.3.3 didn't work out-of-the box. I had to fix bunch of minor issues to make at least the basic stuff work.
I hope you will find this useful. Commit messages an diff should be self explanatory. 
Please consider merging it.
> Fixing a bunch of issues

- publify_core/app/helpers/base_helper.rb
- publify_core/app/views/shared/_google_analytics.html.erb
- publify_core/app/views/shared/_page_header.html.erb
> Fix Google Analytics rendering

- publify_core/Manifest.txt
- publify_core/app/views/articles/_article.html.erb
- publify_core/app/views/articles/_article_author.html.erb
- publify_core/app/views/articles/_protected_article_content.html.erb
- publify_core/app/views/articles/read.html.erb
- publify_core/config/locales/da.yml
- publify_core/config/locales/de.yml
- publify_core/config/locales/en.yml
- publify_core/config/locales/es-MX.yml
- publify_core/config/locales/fr.yml
- publify_core/config/locales/he.yml
- publify_core/config/locales/it.yml
- publify_core/config/locales/ja.yml
- publify_core/config/locales/lt.yml
- publify_core/config/locales/nb-NO.yml
- publify_core/config/locales/nl.yml
- publify_core/config/locales/pl.yml
- publify_core/config/locales/pt-BR.yml
- publify_core/config/locales/ro.yml
- publify_core/config/locales/ru.yml
- publify_core/config/locales/zh-CN.yml
- publify_core/config/locales/zh-TW.yml
- publify_core/spec/controllers/articles_controller_spec.rb
- themes/bootstrap-2/views/articles/read.html.erb
> Fix article excerpt rendering

- .gitignore
- Gemfile
> Development Tools

- publify_core/app/models/blog.rb
- publify_core/app/views/admin/seo/_general.html.erb
- publify_core/app/views/shared/_page_header.html.erb
- publify_core/config/locales/da.yml
- publify_core/config/locales/de.yml
- publify_core/config/locales/en.yml
- publify_core/config/locales/es-MX.yml
- publify_core/config/locales/fr.yml
- publify_core/config/locales/he.yml
- publify_core/config/locales/it.yml
- publify_core/config/locales/ja.yml
- publify_core/config/locales/lt.yml
- publify_core/config/locales/nb-NO.yml
- publify_core/config/locales/nl.yml
- publify_core/config/locales/pl.yml
- publify_core/config/locales/pt-BR.yml
- publify_core/config/locales/ro.yml
- publify_core/config/locales/ru.yml
- publify_core/config/locales/zh-CN.yml
- publify_core/config/locales/zh-TW.yml
- publify_core/lib/publify_core/testing_support/factories.rb
- publify_core/spec/models/configuration_spec.rb
> Always use canonical url

- publify_core/app/controllers/admin/pages_controller.rb
- publify_core/app/views/admin/notes/_form.html.erb
- publify_core/app/views/admin/pages/_form.html.erb
If you try to create a page you'll get an error about an invalid parameter tracker_filter_id.
> Fix broken page creation.

- publify_core/app/models/blog.rb
- publify_core/app/views/shared/_page_header.html.erb
- publify_core/spec/rails_helper.rb
Use `Blog#url_for` to calculate the canonical URL.
> Fixup canonical url

- Gemfile
A very useful tool to check and debug performance issues.
> Add rack-mini-profiler in development

- lib/tasks/replace_textile.rake
- publify_core/app/views/admin/dashboard/index.html.erb
Also warn about and convert Feedback.
> More Textile deprecation

- .github/workflows/ruby.yml
- .rubocop.yml
- Gemfile
- bin/setup
- config/boot.rb
- config/cable.yml
- config/initializers/new_framework_defaults_6_0.rb
- config/puma.rb
- config/routes.rb
- publify_amazon_sidebar/.rubocop.yml
- publify_amazon_sidebar/publify_amazon_sidebar.gemspec
- publify_core/.rubocop.yml
- publify_core/lib/spam_protection.rb
- publify_core/publify_core.gemspec
- publify_core/spec/controllers/theme_controller_spec.rb
- publify_core/spec/helpers/base_helper_spec.rb
- publify_core/spec/rails_helper.rb
- publify_textfilter_code/.rubocop.yml
- publify_textfilter_code/lib/publify_app/textfilter_code.rb
- publify_textfilter_code/publify_textfilter_code.gemspec
- spec/rails_helper.rb
This upgrades Rails to version 6.0, fixes tests, and updates the configuration.
This replaces #955 and includes one of its commits.
> Upgrade to Rails 6.0

- .github/workflows/ruby.yml
- .rubocop_todo.yml
- CHANGELOG.md
- lib/publify_textile_to_markdown.rb
- lib/tasks/release.rake
- lib/tasks/replace_textile.rake
- publify_amazon_sidebar/CHANGELOG.md
- publify_amazon_sidebar/lib/publify_amazon_sidebar/version.rb
- publify_core/CHANGELOG.md
- publify_core/app/models/article.rb
- publify_core/app/models/comment.rb
- publify_core/app/models/content_base.rb
- publify_core/lib/publify_core/version.rb
- publify_textfilter_code/CHANGELOG.md
- publify_textfilter_code/lib/publify_textfilter_code/version.rb
- spec/lib/publify_textile_to_markdown_spec.rb
Update the master branch with the changes from release 9.2.2.
> Pull in changes from 9-2-stable

- Gemfile
- README.md
- publify_amazon_sidebar/publify_amazon_sidebar.gemspec
- publify_core/app/uploaders/resource_uploader.rb
- publify_core/publify_core.gemspec
- publify_textfilter_code/publify_textfilter_code.gemspec
Update to Rails 5.2.6 and replace mimemagic
> Update dependencies/Replace mimemagic

- publify_core/app/views/admin/feedback/article.html.erb
> Link to article from article feedback admin page

- publify_core/app/views/admin/shared/_menu.html.erb
- publify_core/config/locales/da.yml
- publify_core/config/locales/de.yml
- publify_core/config/locales/en.yml
- publify_core/config/locales/es-MX.yml
- publify_core/config/locales/fr.yml
- publify_core/config/locales/he.yml
- publify_core/config/locales/it.yml
- publify_core/config/locales/ja.yml
- publify_core/config/locales/lt.yml
- publify_core/config/locales/nb.yml
- publify_core/config/locales/nl.yml
- publify_core/config/locales/pl.yml
- publify_core/config/locales/pt-BR.yml
- publify_core/config/locales/ro.yml
- publify_core/config/locales/ru.yml
- publify_core/config/locales/zh-CN.yml
- publify_core/config/locales/zh-TW.yml
> Link to blog from admin menu

- publify_core/app/controllers/admin/articles_controller.rb
- publify_core/app/views/admin/articles/_article_list.html.erb
- Fix colspans in article list
- Do not try to set `text_filter` on article, use `text_filter_name` instead
> Miscellaneous admin fixes

- Gemfile
- config/initializers/rack_attack.rb
- publify_core/app/views/admin/resources/index.html.erb
- publify_core/config/locales/da.yml
- publify_core/config/locales/de.yml
- publify_core/config/locales/en.yml
- publify_core/config/locales/es-MX.yml
- publify_core/config/locales/fr.yml
- publify_core/config/locales/he.yml
- publify_core/config/locales/it.yml
- publify_core/config/locales/ja.yml
- publify_core/config/locales/lt.yml
- publify_core/config/locales/nb.yml
- publify_core/config/locales/nl.yml
- publify_core/config/locales/pl.yml
- publify_core/config/locales/pt-BR.yml
- publify_core/config/locales/ro.yml
- publify_core/config/locales/ru.yml
- publify_core/config/locales/zh-CN.yml
- publify_core/config/locales/zh-TW.yml
- Rate-limit Devise logins and password resets
- Correct RuboCop offenses
- Add documentation about use of the media library
> Pull in latest changes from 9-2-stable

- Gemfile
Rails 6.1.6.1 fixes a security issue.
> Require at least Rails 6.1.6.1

- publify_core/app/models/user.rb
- publify_core/lib/publify_core.rb
- publify_core/lib/publify_core/testing_support/factories.rb
- publify_core/publify_core.gemspec
- publify_core/spec/controllers/admin/users_controller_spec.rb
- publify_core/spec/controllers/setup_controller_spec.rb
- publify_core/spec/features/login_spec.rb
- publify_core/spec/features/reset_password_spec.rb
- publify_core/spec/features/setup_spec.rb
- publify_core/spec/features/signup_spec.rb
- publify_core/spec/models/user_spec.rb
This adds validation of passwords using the zxcvbn password strength estimation gem.
> Require user passwords to be strong

- db/migrate/20221012164027_remove_itunes_fields_from_resources.publify_core_engine.rb
- db/schema.rb
- publify_amazon_sidebar/spec/dummy/db/migrate/20221012164101_remove_itunes_fields_from_resources.publify_core_engine.rb
- publify_amazon_sidebar/spec/dummy/db/schema.rb
- publify_core/Manifest.txt
- publify_core/db/migrate/20221012163214_remove_itunes_fields_from_resources.rb
- publify_core/spec/dummy/db/schema.rb
- publify_textfilter_code/spec/dummy/db/migrate/20221012164128_remove_itunes_fields_from_resources.publify_core_engine.rb
- publify_textfilter_code/spec/dummy/db/schema.rb
Removes itunes fields from resources
Issue - https://github.com/publify/publify/issues/1074
> remove itunes fields from resources

- db/migrate/20221010170801_remove_page_caches_table.publify_core_engine.rb
- db/schema.rb
- publify_amazon_sidebar/spec/dummy/db/migrate/20221010170852_remove_page_caches_table.publify_core_engine.rb
- publify_amazon_sidebar/spec/dummy/db/schema.rb
- publify_core/Manifest.txt
- publify_core/db/migrate/20221010092846_remove_page_caches_table.rb
- publify_core/spec/dummy/db/schema.rb
- publify_textfilter_code/spec/dummy/db/migrate/20221010170831_remove_page_caches_table.publify_core_engine.rb
- publify_textfilter_code/spec/dummy/db/schema.rb
Issue: https://github.com/publify/publify/issues/1075
Remove pages_caches table
> remove page_caches table

- CHANGELOG.md
- Gemfile
- Depend on released publify gems
- Prepare CHANGELOG for release 10.0.0
> Prepare Publify 10.0.0 for release

- CHANGELOG.md
- Gemfile
- Depend on released publify gems
- Prepare CHANGELOG for release 10.0.1
> Prepare Publify 10.0.1 for release

- Gemfile
Straight irb is now good enough for debugging.
> Remove dependency on pry
